language: node_js
node_js:
- '0.10'
before_deploy:
- npm run build
deploy:
  provider: s3
  skip_cleanup: true
  access_key_id: AKIAJ34HS66AADLVVKGA
  secret_access_key:
    secure: WgM3OfmSIXKJPGLY7ixNxn5Abz6JiAMtKsPCykRNwLRtZsyZ6gnWDbMog703q8ULwxrR9eaq34q0bGfHhZLTOQfdG21YYWOG3AkdJNhq9Jgf4YVAhs7GILtvhrJmZtWSnIf6wzTOtEsCUfXE9IWdz0sahrenqXviugOWi/d+7Jw=
  bucket: webmaker-app-publisher-staging
  local-dir: assets
  on:
    branch: master
    repo: mozillafordevelopment/webmaker-app-publisher
