language: node_js
node_js:
- '0.10'
before_deploy:
- npm run build
deploy:
# webmaker-app-publisher.mofodev.net
- provider: s3
  skip_cleanup: true
  access_key_id: AKIAJMJ4R6KFKGVDH74A
  secret_access_key:
    secure: fn+eO5hoSdsLLAjOtPQmTzZ07LufjcT6bbMXmSne0jxLqsht9Z/xUjTF+WVCP0Y4W/ON2+qQ0xs+fGOqjj7sWYnvZ+JOvYR0HDKl0UTuzMcWInqx72w+8HEoEax1Burg++a+t/y2PVvz8cGs0Y65N0FRCwbG8AA6iBt5f7r8wq4=
  bucket: webmaker-app-publisher-staging
  local-dir: assets
  on:
    branch: master
    repo: mozilla/webmaker-app-publisher
# webmaker-publisher.mofostaging.net
- provider: s3
  skip_cleanup: true
  access_key_id: AKIAIS5Q7XHEIDVY7BPQ
  secret_access_key:
    secure: "kaVii9qUyRA0fz6dMmBJ78XhjzAbV68pbabKBv9LznrZjwrx+UHR2O3CHiy8pH+Cpan/yNSabTqIg3t6amcXkngoLfa7m/3QUDhSKzFs2GZa1Jf6TywJ+de59RGwWrh8Z7aQjiGJiWnx9xVIaefkua6CDKLfvTTrdqYaklyDYdM="
  bucket: webmaker-publisher-staging
  local-dir: assets
  on:
    branch: master
    repo: mozilla/webmaker-app-publisher
